<a href="https://colab.research.google.com/github/Vonewman/Deep_Learning_models_with_pytorch/blob/master/01_PyTorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

## Tensors
At it's core Pytorch is a library for processing tensors. A tensor is a number, vector, matrix or any n-dimensional array. Let's create a tensor with a single number.

In [2]:
# Number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [4]:
# Vector
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [5]:
# Matrix
t3 = torch.tensor([[5., 6], [7, 8], [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [6]:
# 3-dimensional array
t4 = torch.tensor([
                   [[11, 12, 13], 
                    [13, 14, 15]],
                   [[15, 16, 17],
                    [17, 18, 19.]]
])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

Tensor can have any number of dimensions, and different lengths along each dimension. We can inspect along each dimension using the `.shape` of a tensor.

In [7]:
t1.shape

torch.Size([])

In [8]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

## Tensor Operations and Gradients

We can combine tensors with the usual arithmetic operations. Let's look an example:

In [9]:
# Create tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

We've created 3 tensors `x` `w` and `b`.
Let's create a new tensor `y` by combining these tensors.

In [10]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, `y` is a tensor with the value `3 * 4 + 5 = 17`. What makes PyTorch special is that we can automatically compute the derivate of `y` the tensors that have `requires_grad` set to `True` w and b. To compute the derivatives we can can call the `.backward` method on your result `y`.

In [11]:
# computes derivatives
y.backward()

The derivates of `y` the output are stored in the `.grad`of the prospective tensors.

In [12]:
# Display gradients
print("dy/dx:", x.grad)
print("dy/dw:", w.grad)
print("dy/db:", b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


## Interoperability with NumPy

In [13]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [14]:
# convert the numpy array to a torch tensor
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [15]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [16]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])