<a href="https://colab.research.google.com/github/Vonewman/Deep_Learning_models_with_pytorch/blob/master/intro_to_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# First import torch
import torch

In [0]:
def activation(x):
  """
  Sigmoid activation function

  Arguments
  ---------------------------
  torch.Tensor
  """
  return 1./(1 + torch.exp(-x))

In [0]:
### Generate some data
torch.manual_seed(7)  # Set the random seed

# Features are 5 random normal variables again
features = torch.randn((1, 5))

# True weights for our data, random normal variables again
weights = torch.randn_like(features)

# and a true bias term
bias = torch.randn((1, 1))

In [19]:
y = activation(torch.sum(weights * features) + bias)

print(y)

tensor([[0.1595]])


In [20]:
# calculate the output of our little network
y = activation(torch.mm(features, weights.view(5, 1)) + bias)
print(y)

tensor([[0.1595]])


In [0]:
### Generate some data
torch.manual_seed(7)

# Features are random variables
features = torch.randn((1, 3))

# define the size of each layer in our network
n_input = features.shape[1]
n_hidden = 2
n_output = 3

# Weights for input to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias term for hidden and output layer
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [24]:
h = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(h, W2) + B2)
print(output)

tensor([[0.2400, 0.9499, 0.9670]])
