<a href="https://colab.research.google.com/github/Vonewman/Deep_Learning_models_with_pytorch/blob/master/pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pytorch Tensors - Neural Network Programming

In [35]:
import torch
import numpy as np



### Tensor class

Tensors in Pytorch are represented using the `torch.Tensor`



In [36]:
t = torch.Tensor()
type(t)

torch.Tensor

## Tensor Attributes



In [37]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


In [38]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [39]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([1., 2., 3.])

In [40]:
t1.dtype

torch.int64

In [41]:
t2.dtype

torch.float32

In [42]:
t1 + t2

tensor([2., 4., 6.])

In [43]:
t1 = torch.tensor([1, 2, 3])
t2 = t1.cuda()

In [44]:
t1.device

device(type='cpu')

In [45]:
t2.device

device(type='cuda', index=0)

In [46]:
# t1 + t2 # ERROR!

## Creating options using data

In [47]:
data = np.array([1, 2, 3])
data

array([1, 2, 3])

In [48]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [49]:
torch.tensor(data)

tensor([1, 2, 3])

In [50]:
torch.as_tensor(data)

tensor([1, 2, 3])

In [51]:
torch.from_numpy(data)

tensor([1, 2, 3])

## Creation option without data

In [52]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [53]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

In [54]:
torch.ones(2, 2)

tensor([[1., 1.],
        [1., 1.]])

In [55]:
torch.rand(2, 2)

tensor([[0.8215, 0.7007],
        [0.4341, 0.3025]])