<a href="https://colab.research.google.com/github/Vonewman/Deep_Learning_models_with_pytorch/blob/master/Single_layer_neural_networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import torch

## Activation function

In [18]:
def sigmoid(x):
    """
    Sigmoid activation function

    Argumenets:
    -----------
    x: torch.Tensor
    """
    return 1/(1 + torch.exp(-x))

### Generate some data

In [19]:
torch.manual_seed(4)  # Set the random so things are predictable

# Features are three random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

## Calculate the output of this network using the weights and bias tensors

In [20]:
y = sigmoid(torch.sum(features * weights) + bias)
print(y)
y = sigmoid((features * weights).sum() + bias)
print(y)

tensor([[0.9916]])
tensor([[0.9916]])


## Calculate the output of this network using matrix multiplication

In [21]:
out = sigmoid(torch.mm(features, weights.view(5, 1)) + bias)
print(out)

tensor([[0.9916]])


### Stack them up!

That's how you can calculate the output for a single neuron. The real power of this algorithm happens when you start stacking these individual units into layers and stacks of layers, into a network of neurons. The output of one layer of neurons becomes the input for the next layer. With multiple input units and output units, we now need to express the weights as a matrix.

<img src='https://github.com/udacity/deep-learning-v2-pytorch/blob/master/intro-to-pytorch/assets/multilayer_diagram_weights.png?raw=1' width=450px>

The first layer shown on the bottom here are the inputs, understandably called the **input layer**. The middle layer is called the **hidden layer**, and the final layer (on the right) is the **output layer**. We can express this network mathematically with matrices again and use matrix multiplication to get linear combinations for each unit in one operation. For example, the hidden layer ($h_1$ and $h_2$ here) can be calculated 

$$
\vec{h} = [h_1 \, h_2] = 
\begin{bmatrix}
x_1 \, x_2 \cdots \, x_n
\end{bmatrix}
\cdot 
\begin{bmatrix}
           w_{11} & w_{12} \\
           w_{21} &w_{22} \\
           \vdots &\vdots \\
           w_{n1} &w_{n2}
\end{bmatrix}
$$

The output for this small network is found by treating the hidden layer as inputs for the output unit. The network output is expressed simply

$$
y =  f_2 \! \left(\, f_1 \! \left(\vec{x} \, \mathbf{W_1}\right) \mathbf{W_2} \right)
$$

## Generate some data

In [22]:
torch.manual_seed(4)

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]
n_hidden = 2  # number of hidden units
n_output = 1  # number of outputs units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [25]:
h = sigmoid(torch.mm(features, W1) + B1)
output = sigmoid(torch.mm(h, W2) + B2)
print(B2)

tensor([[0.0513]])


## Numpy to Torch and back

Special bonus section! PyTorch has a great feature for converting between Numpy arrays and Torch tensors. To create a tensor from a Numpy array, use `torch.from_numpy()`. To convert a tensor to a Numpy array, use the `.numpy()` method.

In [26]:
import numpy as np
a = np.random.rand(4, 3)
a

array([[0.90238734, 0.14444256, 0.83502947],
       [0.41468495, 0.34145158, 0.43205009],
       [0.37113047, 0.90584576, 0.47130238],
       [0.65737766, 0.67023806, 0.00990078]])

In [27]:
b = torch.from_numpy(a)
b

tensor([[0.9024, 0.1444, 0.8350],
        [0.4147, 0.3415, 0.4321],
        [0.3711, 0.9058, 0.4713],
        [0.6574, 0.6702, 0.0099]], dtype=torch.float64)

In [28]:
b.numpy()

array([[0.90238734, 0.14444256, 0.83502947],
       [0.41468495, 0.34145158, 0.43205009],
       [0.37113047, 0.90584576, 0.47130238],
       [0.65737766, 0.67023806, 0.00990078]])

In [29]:
b.mul_(2) # multiplication in-place

tensor([[1.8048, 0.2889, 1.6701],
        [0.8294, 0.6829, 0.8641],
        [0.7423, 1.8117, 0.9426],
        [1.3148, 1.3405, 0.0198]], dtype=torch.float64)

In [30]:
# Numpy array matches new values from Tensor
a

array([[1.80477468, 0.28888512, 1.67005893],
       [0.82936989, 0.68290316, 0.86410019],
       [0.74226095, 1.81169152, 0.94260475],
       [1.31475532, 1.34047612, 0.01980156]])