<a href="https://colab.research.google.com/github/Vonewman/Deep_Learning_models_with_pytorch/blob/master/Single_layer_neural_networks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

## Activation function

In [3]:
def sigmoid(x):
    """
    Sigmoid activation function

    Argumenets:
    -----------
    x: torch.Tensor
    """
    return 1/(1 + torch.exp(-x))

### Generate some data

In [5]:
torch.manual_seed(4)  # Set the random so things are predictable

# Features are three random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

## Calculate the output of this network using the weights and bias tensors

In [8]:
y = sigmoid(torch.sum(features * weights) + bias)
print(y)
y = sigmoid((features * weights).sum() + bias)
print(y)

tensor([[0.9916]])
tensor([[0.9916]])


## Calculate the output of this network using matrix multiplication

In [13]:
out = sigmoid(torch.mm(features, weights.view(5, 1)) + bias)
print(out)

tensor([[0.9916]])
