<a href="https://colab.research.google.com/github/Vonewman/Deep_Learning_models_with_pytorch/blob/master/Tensor_in_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
t = torch.tensor([1,2,3])
t

tensor([1, 2, 3])

In [3]:
t = t.cuda()
t

tensor([1, 2, 3], device='cuda:0')

# Shape

In [4]:
dd = [
      [1, 2, 3],
      [4, 5, 6],
      [7, 8, 9]
]

In [5]:
t = torch.tensor(dd)
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
type(t)

torch.Tensor

In [7]:
t.shape

torch.Size([3, 3])


A tensor's shape is important



In [8]:
t.reshape(1, 9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [9]:
t.reshape(1, 9).shape

torch.Size([1, 9])

In [10]:
t

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])