<a href="https://colab.research.google.com/github/Vonewman/Deep_Learning_models_with_pytorch/blob/master/Pytorch-Basics-for-ML/Two_Dimensional_Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import torch

In [20]:
a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [21]:
A = torch.tensor(a)

In [22]:
A.ndimension()

2

In [23]:
A.shape

torch.Size([3, 3])

In [24]:
A.size()

torch.Size([3, 3])

In [25]:
A.numel() # number of elements

9

## Indexing and Slicing of 2D Tensors

In [26]:
A[0][1]

tensor(12)

In [27]:
A[0, 0:2]

tensor([11, 12])

In [28]:
A[1:3, 2]

tensor([23, 33])

## Basic Operation in 2D-Tensor

* Addition

In [29]:
X = torch.tensor([[1, 0], [0, 1]])
Y = torch.tensor([[2, 1], [1, 2]])
Z = X + Y

In [30]:
Z

tensor([[3, 1],
        [1, 3]])

* Multiply by a scalar

In [31]:
Y = torch.tensor([[2, 1], [1, 2]])
Z = 2 * Y

In [32]:
Z

tensor([[4, 2],
        [2, 4]])

* Multiply two scalar of the same dimension

In [33]:
X = torch.tensor([[1, 2], [2, 1]])
Y = torch.tensor([[2, 1], [1, 2]])
Z = X * Y

In [34]:
Z

tensor([[2, 2],
        [2, 2]])

* Matrix Multiplication

In [35]:
A = torch.tensor([[0, 1, 1], [1, 0, 1]])
B = torch.tensor([[1, 1], [1, 1], [-1, 1]])
C = torch.mm(A, B)

In [36]:
C

tensor([[0, 2],
        [0, 2]])